import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/next-auth-provider";
import NextThemeProvider from "@/providers/theme-provider";
import GlobalState from "@/context";
import Header from "@/components/header";
import { cn } from "@nextui-org/react";
import { Toaster } from "@/components/ui/toaster"
const inter = Inter({ subsets: ["latin"] });
import {ChakraProvider} from '@chakra-ui/react'

export const metadata: Metadata = {
  title: "Canals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen font-sans ${inter.className}`}>
        <NextThemeProvider>
          <NextAuthProvider>
            <GlobalState>
                
              <Header />
              {children}
              <Toaster />
            </GlobalState>
          </NextAuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
